name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker_k8s/app_python/
          file: ./docker_k8s/app_python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/app:2.0

      -
        name: Atualizando a infra 
        
        run: sed -i "s/didis/app:1.0/didis/app:2.0/g" ./docker_k8s/app_python/k8s/app_deployment.yaml
      -
        name: push change
        uses: actions/checkout@v2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: ./docker_k8s/app_python/k8s/app_deployment.yaml
          destination_repo: diogolimaelven/elvenworks_formacao_sre
          destination_branch: main
          destination_folder: .
          user_email: diogo.lima@elven.works
          user_name: diogo.lima
          commit_message: update image version ${{ steps.get_version.outputs.VERSION }} in yml file  

