name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker_k8s/app_python/
          file: ./docker_k8s/app_python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/app:2.0

      -
        name: Atualizando a infra 
        
        run: cd ./docker_k8s/app_python/k8s/ && sudo sed 's/didis\/app:1.0/didis\/app:2.0/g' app-deployment.yaml && cat app-deployment.yaml && cd
      -
        name: push change
        uses: actions/checkout@v3
        
        with:
          repository: 'diogolimaelven/elvenworks_formacao_sre'
          ref: main
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - run: |
            git add *
            git config user.email diogo.lima@elven.works
            git config user.name diogo.lima
            git commit -m update image version ${{ steps.get_version.outputs.VERSION }} in yml file
            git push
          
